#!/bin/sh

setxkbmap -option compose:rctrl
setxkbmap -option altwin:swap_alt_win
setxkbmap -option ctrl:swapcaps     # Swap Left Control and Caps Lock

if [ -z "$(pgrep nm-applet)" ] ; then nm-applet --sm-disable & fi
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &
SXHKD_SHELL=/bin/bash sxhkd &
nitrogen --restore &
# dunst -conf ~/.config/dunst/dunstrc &
if [ -z "$(pgrep dropbox )" ] ; then dropbox start & fi
# if [ -z "$(pgrep tilda)" ] ; then tilda & fi

# gnupg keyring agent
# ensure it's started so SSH will work
# https://www.gnupg.org/faq/whats-new-in-2.1.html#autostart
# dbus-update-activation-environment --systemd DISPLAY
# gpgconf --launch gpg-agent
# export "SSH_AUTH_SOCK=/run/user/$(id -u)/gnupg/S.gpg-agent.ssh"

if [ -e ~/.scripts/hotplug-dp.sh ]; then
  (
  sleep .2;
  sudo -E -u shwsun ~/.scripts/hotplug-dp.sh desktop;
  # sudo -E -u jethros ~/.scripts/hotplug-dp.sh desktop;
  ) &
fi
# sudo -E -u shwsun ~/.scripts/hotplug-dp.sh desktop;

# =============================
#   bspwm things
# =============================

bspc monitor HDMI-1 -d null term web reader I II III IRC emacs fun
bspc desktop --focus term

bspc config border_width         2
bspc config window_gap           20
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# desktop specific settings
bspc desktop "^3" --layout monocle
bspc config -d "^3" border_width 0
bspc config -d "^3" window_gap 0
bspc config -d "^3" top_padding 0
bspc desktop "^4" --layout monocle
bspc config -d "^4" border_width 0
bspc config -d "^4" window_gap 0
bspc config -d "^4" top_padding 0

# bspwm rule
bspc rule -a Alacritty state=tiled

bspc rule -a Emacs desktop='^1' state=tiled
bspc rule -a zoom desktop='^1'
bspc rule -a Google-chrome desktop='^1'

bspc rule -a firefox desktop='^3' follow=on state=tiled
bspc rule -a firefoxdeveloperedition desktop='^3' follow=on state=tiled

bspc rule -a Zathura desktop='^4' follow=on state=tiled
bspc rule -a MuPDF desktop='^4' state=tiled

bspc rule -a PCManFM desktop='^5' follow=on state=tiled
bspc rule -a Thunar desktop='^5' state=tiled

# bspc rule -a Roam Research desktop='^7'

bspc rule -a MineTime desktop='^8' follow=on state=tiled
bspc rule -a Wireshark desktop='^8' state=tiled
bspc rule -a qBittorrent desktop='^8' state=tiled
bspc rule -a Zotero desktop='^8' state=tiled

bspc rule -a Discord desktop='^8' state=tiled
bspc rule -a Slack desktop='^8' state=tiled
bspc rule -a Microsoft Teams desktop='^8' state=tiled
bspc rule -a Microsoft Teams - Preview desktop='^8'

bspc rule -a Code desktop='^9' follow=on state=tiled
bspc rule -a Obsidian desktop='^9' state=tiled

bspc rule -a polybar border=off manage=off

# Any popup type terminal windows
bspc rule -a "*:popup_window" state=floating rectangle=825x500 center
bspc rule -a Pinentry state=floating
bspc rule -a Pilorama state=floating
bspc rule -a Tilda state=floating
bspc rule -a GlobalProtect state=floating

# Any popup type terminal windows large
bspc rule -a "*:popup_window_large" state=floating rectangle=1500x750 center
