#!/bin/sh

# =============================
#  Setup
# =============================

## BEHAVIOR

# screen lock
/usr/bin/xautolock -time 450 -locker /usr/bin/i3lock-fancy-multimonitor -detectsleep &

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then nm-applet --sm-disable & fi

# sxhkd uses the shell so it can't be fish
SXHKD_SHELL=/bin/bash sxhkd &

nitrogen --restore &

# dunst to display messages
dunst -conf ~/.config/dunst/dunstrc &

# =============================
# bspwm things
# =============================

bspc monitor eDP1 -d I
bspc monitor HDMI1 -d II III IV V VI VII VIII IX X
bspc desktop --focus II

bspc config border_width         2
bspc config window_gap           10
bspc config focused_border_color \#3c3836
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# desktop specific settings
bspc desktop "^3" --layout monocle
bspc config -d "^3" border_width 0
bspc config -d "^3" window_gap 0
bspc config -d "^3" top_padding 0

bspc rule -a Alacritty state=tiled

bspc rule -a zoom desktop='^1'

bspc rule -a firefoxdeveloperedition desktop='^3' follow=on state=tiled

bspc rule -a Zathura desktop='^4' follow=on state=tiled
bspc rule -a Evince desktop='^4' state=tiled

bspc rule -a Code desktop='^9' follow=on state=tiled
bspc rule -a Emacs desktop='^9' state=tiled
# bspc rule -a Nautilus desktop='^9' follow=on state=tiled
# bspc rule -a Nemo desktop='^9' follow=on state=tiled
bspc rule -a Wireshark desktop='^9' state=tiled
bspc rule -a Zotero desktop='^9' state=tiled
bspc rule -a qBittorrent desktop='^9' state=tiled
# bspc rule -a qbittorrent desktop='^9' state=tiled

bspc rule -a Discord desktop='^10'
# bspc rule -a Evolution desktop='^10'
bspc rule -a Slack desktop='^10'

bspc rule -a polybar border=off manage=off

# Any popup type terminal windows
bspc rule -a "*:popup_window" state=floating rectangle=825x500 center

# Any popup type terminal windows large
bspc rule -a "*:popup_window_large" state=floating rectangle=1500x750 center
